### ISSUE TITLE
Add a flag to control whether or not to generate a Root CA

### ISSUE THREAD

**Issue by fgiorgetti** [msgqe/ansible-ssl-generation#1]

**Comment by michalxo** [comment]
So I believe user will point this role to appropriate root CA, correct? 
We don't want to have self-signed certificates, right?

**Comment by fgiorgetti** [comment]
For router scenarios, that is exactly what we are doing. Generating
self-signed certificates.
So we need it here.

**Comment by michalxo** [comment]
Done with the latest commit.
https://github.com/msgqe/ansible-ssl-generation/commit/d30817fe5b6c49bcc068089c27c8072eaee5ef5a

**Comment by fgiorgetti** [comment]
@michalxo I looked into the recent changes and I do not see the generate-root-ca.yml task being invoked anywhere. Should this be reopened?
