### ISSUE TITLE
Add a flag to control whether to copy certificates to remote nodes

### ISSUE THREAD

**Issue by fgiorgetti** [msgqe/ansible-ssl-generation#2]
Just as a side note. Saying it, because in our current scenario we do not need to copy it anywhere. Instead we have to create a secret on OCP based on the existing certificate (which remains at localhost only).

**Comment by michalxo** [comment]
You mean do not copy **anything** at all to the nodes?

**Comment by fgiorgetti** [comment]
Correct. Of course that the default action should be to copy them, but this
could be turned off optionally.
